### ISSUE TITLE
[BUG] Not possible to create another annotation table in another worksheet

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/Swate#58] opened 2020-11-25 17:14 UTC
**Describe the bug**
If one annotation table is created, it is not possible to create another one in another worksheet.

**To Reproduce**
1. Open a new excel file
2. Open _CSBAnnotator_ in _Data_ tab
3. Click _create annoation_ [sic] _table_
4. Create another worksheet
5. In CSBAnnotator tab, there is no option to create another annotation table. This does not change if the Add-In or the excel file is reloaded

**Expected behavior**
_Create annotation table_ button should appear when switching to a worksheet without an annotation table.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47781170/100259529-9b9f6f00-2f48-11eb-8914-f8ffb174bc9e.png)
New excel file without annotation table. It is possible to add a new one.

![grafik](https://user-images.githubusercontent.com/47781170/100259613-b07c0280-2f48-11eb-9539-7ab588e7630d.png)
Annotation table created.

![grafik](https://user-images.githubusercontent.com/47781170/100259679-c4276900-2f48-11eb-96f6-ad818e5646a2.png)
Not able to add another annotation table, even after reloading the Add-In.

**OS and framework information:**
 - OS: Windows 10 Home
 - OS Version: 10.0, Build 18363
 - .Net core SDK version: 5.0.100

**Additional context**
2 things to notice:
1. _getActiveWorksheet_ method/function seems to not work properly.
2. Tables are not assigned to the specific worksheets in which they are located. Instead, it is only their reference which is assigned to the worksheet.

**Comment by Freymaurer** [comment] 2020-11-26 10:40
Ok first testing showed that the `tables` element of a worksheet is misleading. To correctly document this issue, i'll write a short summary here.

```fsharp
let exampleExcelFunction () =
    Excel.run(fun context ->
        let sheet = context.workbook.worksheets.getActiveWorksheet()
        let t = sheet.load(U2.Case2 (ResizeArray[|"tables"; "name"|]))
        let table = t.tables.getItemOrNullObject("annotationTable")
        let n = t.name
        context.sync()
            .``then``( fun _ ->
                let isExisting = not table.isNullObject
                sprintf "%A -> %s" isExisting n
        )
    )
```

This is a slightly changed variant of our function to check if the active worksheet contains an annotation table. I only added the `let n = t.name` part and added it to the load function. Contrary to my expectation it threw an error with:

> The property 'name' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.

```fsharp
let exampleExcelFunction () =
    Excel.run(fun context ->
        let sheet = context.workbook.worksheets.getActiveWorksheet()
        let t = sheet.load(U2.Case2 (ResizeArray[|"tables"; "name"|]))
        let table = t.tables.getItemOrNullObject("annotationTable")
        context.sync()
            .``then``( fun _ ->
                let n = t.name
                let isExisting = not table.isNullObject
                sprintf "%A -> %s" isExisting n
        )
    )
```

This on the other hand works. For me this is a sign that not the correct tables are loaded. 

![image](https://user-images.githubusercontent.com/39732517/100340582-b838b700-2fdb-11eb-8d88-d9a8e934e42f.png)

As the description is rather clear i think we should open an issue about this.

> Tables are not assigned to the specific worksheets in which they are located. Instead, it is only their reference which is assigned to the worksheet.

I also tested creating another annotationTable by hand (in another worksheet) and got the error that a table with the name already exists. So we need to add the worksheet name to the table name.

**Comment by Freymaurer** [comment] 2020-11-26 11:03
Forget what i just wrote, `tables` works as intended. But `getItemOrNullObject` seems to search all tables instead of the ones on which it is used.

**Comment by kMutagene** [comment] 2020-11-26 12:03
> Forget what i just wrote, tables works as intended. But getItemOrNullObject seems to search all tables instead of the ones on which it is used.

I do not get what you mean. `tables` seems to be a global object containing all tables in the workbook. We just have to use names for the tables that are unique and map them to the respective sheets.

**Comment by Freymaurer** [comment] 2020-11-26 12:09
Well you do load tables on the active worksheet. Therefore you will only get the tables that really are in the active worksheet. I tested this with the following:

```fsharp
let exampleExcelFunction () =
    Excel.run(fun context ->
        let sheet = context.workbook.worksheets.getActiveWorksheet()
        let t = sheet.load(U2.Case2 (ResizeArray[|"tables"|]))
        let tableItems = t.tables.load(propertyNames=U2.Case1 "items")
        context.sync()
            .``then``( fun _ ->
                let annoTableOpt =
                    tableItems.items
                    |> Seq.toArray
                    |> Array.map (fun x -> x.name)
                    |> Array.tryFind (fun x -> x.StartsWith "annotationTable")
                sprintf "Found Tables: %A" annoTableOpt
        )
    )
```
![image](https://user-images.githubusercontent.com/39732517/100349181-5894d880-2fe8-11eb-99e2-3bda9ba93a41.png)

This is the result of the function above. Note that i have a second worksheet with another table in my workbook.

**Comment by kMutagene** [comment] 2020-11-26 12:56
So you reference table definitions in the current worksheet i guess. the tables part of the underlying XML is seperated from sheets themselves:

> The following XML defines the worksheet and is contained in the "sheet1.xml" file. The worksheet XML file contains the actual data displayed in the table, and contains the tablePart element that references the "table1.xml" file, which contains the table definition.

> The following XML defines the table and is contained in the "table1.xml" file. The table XML file defines how the range of the table and how the table looks, and defines any autofilters for the table.

```XML
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="Table1" displayName="Table1" ref="A1:C4" totalsRowShown="0">
        <autoFilter ref="A1:C4"/>
        <tableColumns count="3">
            <tableColumn id="1" name="Column1"/>
            <tableColumn id="2" name="Column2"/>
            <tableColumn id="3" name="Column3"/>
        </tableColumns>
        <tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/>
    </table>
```

see https://docs.microsoft.com/de-de/office/open-xml/working-with-tables#spreadsheetml-example

It also seems like you can get much of the data model information about the annotation tables from these tags, as they contain a lot of usefull stuff as attributes (e.g. table range)

This also explains why you have to use globally unique keys for tables.

**Comment by Freymaurer** [comment] 2020-11-26 21:02
Should be working as intended and will be in production from release 0.1.2 onwards.

**Closed by Freymaurer** 2020-11-26 21:02 UTC
Labels: Area: Excel, Area: Frontend, Priority: Critical, Type: Bug
